config/routes.rb
Rails.application.routes.draw do
 

get 'home/index'
# resources :user
  resources :tasks
resources :team_lead
resources :department
  #get 'team_lead/show'
   
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post '/tasks' => "tasks#create"
  root 'home#index'
  post '/department/change_time'
  get '/email' => "home#send_email"
  get '/insert_checkbox' => 'tasks#set_checkbox'
  post '/department/:id' => "department#change_time"
end



 

app/models/department.rb
class Department < ApplicationRecord
	has_many :users
end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController

	def create
    	@dept = Department.find(params[:id])
    	if @dept.save
        	redirect_to root_path, notice: "Successfully created."
    	else
     	    render :action => 'edit'
    	end
    end

	def change_time
		@departments = Department.find(params[:department][:id])
		if(@departments.update(params.require(:department)
								.permit(:timings, :timings_end)))
		redirect_to department_change_time_url	
		else
			render plain: "error"
		end
	end
	
	def show
		@departments = Department.all
	end

end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/views/department/show.html.erb
<head>
<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body style="background-image:url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBBEXXmQ3THutGt2YCWLPfc3bG7hpDl8lpA5qCN1Pp8fiwT04X7g)">

<%= render :template => "/home/nav" %>
<div class="container" >
<table class = "table" style="background-image: url(http://www.bestcoaching.com.mx/cartas/wp-content/uploads/2016/01/black-background-92475-1024x640.jpg)" >
	<thead align="center">
		<tr>
		<th> 
			<font color="grey"><b>DEPARTMENT NAME</b></font>
		</th>
		<th>
			<font color="grey"><b>START TIME</b></font>
		</th>
		<th>
			<font color="grey"><b>END TIME</b></font>
		</th>
		<th>
			<font color="grey"><b></b></font>
		</th>
		</tr>
	</thead>
	
	<%@departments.each do |d|%>
	
	<tbody align="center">
		<tr>
			<td>
				<font color="grey">	<%= d.dept_name%> </font>
			</td>

			<td align="center">
				<%=form_for(:department, url: department_path) do |f| %>
				<%= f.time_select :timings, :value => d.timings, :default => d.timings %>
				<%= f.hidden_field :id, :value => d.id %>
				<%=f.submit :Change, class: "btn btn-primary" %>
				<%end%>
			</td>
			<td>
				<%=form_for(:department, url: department_path) do |f| %>
				<%= f.time_select :timings_end, :value => d.timings_end, :default => d.timings_end %>
				<%= f.hidden_field :id, :value => d.id %>
				<%=f.submit :Change, class: "btn btn-primary" %>
				<%end%>
			</td>
			<td>
				
				
				
			</td>
		</tr>
	</tbody>

	<%end%>
</table>
</div>


		
</body>