config/routes.rb
Rails.application.routes.draw do
 

get 'home/index'
# resources :user
  resources :tasks
resources :team_lead
resources :department
  #get 'team_lead/show'
   
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post '/tasks' => "tasks#create"
  root 'home#index'
  post '/department/change_time'
  get '/email' => "home#send_email"
  get '/insert_checkbox' => 'tasks#set_checkbox'
  post '/department/:id' => "department#change_time"
end



 

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		if (user_signed_in?)
      		 @user=current_user
     		 @tasks = current_user.tasks
     		 # @date = @tasks.order(:date).group(:date)
     		 # @dates = @date.where.not(completed: nil).count
         @dates = @tasks.order(:date).map(&:date).uniq
     		 @tasks_perday = @tasks
     
  		else
  		  redirect_to new_user_session_path
 		 end
 	 end

	  def send_email
  		UserMailer.send_email.deliver_now
  		redirect_to root_path
	  end

   

end

app/helpers/home_helper.rb
module HomeHelper
	def show_users_path_if_admin
		(if logged_in?(:admin, :manager)
			("Note: Our systems have detected that you are an admin. You can ") +
			(link_to "view all users", custom_users_path) +
			(" here <br>")
		else
			""
		end).html_safe
	end
	def current_time_exceeds_threshold
		if(Time.now.hour > 11)
			return true
		else
			return false
		end
	end
end

app/views/home/index.html.erb
<!-- <h1> Welcome  <%= current_user.name%></h1> -->
<head>  
<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->

</head>


<body style="background-image:url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBBEXXmQ3THutGt2YCWLPfc3bG7hpDl8lpA5qCN1Pp8fiwT04X7g)">
	<%= render :template => "/home/nav" %>

<!-- <header align="center">
<% if logged_in?(:admin, :manager)%>
	
	<%=link_to "CHANGE TIMINGS" , department_change_time_path%><br>
<%end%>
</header> -->


<br>
<br>
<div class="container" align="center">
	<%if(@tasks_perday.present?)%>
		<font color="white">Tick what you have achieved today: </font>
	<%end%>
<%if(@tasks_perday.present?) %>

		<div class = "form-group">
			<% @tasks_perday.each do |task|%>
				<% if task.checkbox== false %>
					<input type="checkbox" id="checkbox-users-show" onclick="sendCheckRequest(<%=task.id%>)">
						</font><font color="white"><%=task.what_to_do%><br></font>
				<%end%>
				
			<%end%>
		</div>
	 	
	<%=form_for(:task, url: tasks_path) do |f| %>
		<div class = "form-group">
			<font color="white"><%=f.label "ADD MORE TASKS"%></font>
			<font color="white"><%=f.text_field :what_to_do, id: "what_to_do-form-field", class: "form-control"%></font>
		</div>
		<%=f.submit :Submit, class: "btn btn-primary"%>
	<%end%>


<%else%>

	<%=form_for(:task, url: tasks_path) do |f| %>
		<div class = "form-group">
			<font color="white"><%=f.label "TASKS FOR TODAY"%></font>
			<font color="white"><%=f.text_field :what_to_do, id: "what_to_do-form-field", class: "form-control"%></font>
			
		</div>
		<%=f.submit :Submit, class: "btn btn-primary"%>
	<%end%>

<% end %>

</div>
<br>

<div class="container" >
<table class = "table" style="background-image: url(http://www.bestcoaching.com.mx/cartas/wp-content/uploads/2016/01/black-background-92475-1024x640.jpg)" >
	<thead align="center">
		<tr>
		<th> 
			<font color="grey"><b>DATE</b></font>
		</th>
		<th>
			<font color="grey"><b>SCHEDULED TASK</b></font>
		</th>
		<th>
			<font color="grey"><b>END TASK</b></font>
		</th>
		</tr>
	</thead>
	
	<% @dates.each do |date| %>
	<tbody align="center">
		<tr>
			<td>
				<font color="grey">	<%= date %> </font>
			</td>

			<td align="center">
				<%@tasks.where(date: date).each do |task|%> 
				 <% if !(task.checkbox)%>
				 	<font color="white"><%=task.what_to_do%></font></br>
				    <font color="grey">  </font> <font color="grey" align="center"><%= (task.created_at).localtime.in_time_zone('Asia/Kolkata').strftime("%I:%M %P") %> </font><br>
				 <%end%>
				<%end%>
			</td>
	
			<td>
				<%@tasks.where(completed: date).each do |task|%>
				<%if(task.checkbox)%>
				  
					<%= link_to task.what_to_do , task_path(task.id), :class => "submit_button", :onclick => 'return openPopup(this);' %><br>
					<!-- <font color="grey" align="center">Started at:<%= (task.created_at).localtime.to_date.strftime("%B %d %Y")%> <%=(task.created_at).localtime.strftime("%I:%M %P") %> <br> End Time:<%= (task.updated_at).localtime.strftime("%I:%M %P") %></font> -->
					<!-- <font color="grey">(<%= (task.updated_at).localtime.to_date.strftime("%B %d %Y")%></font> <font color="grey"><%= (task.updated_at).localtime.strftime("%I:%M %P") %> )</font><br> -->
					
				<%end%>
				<%end%>
			</td>
		</tr>
	</tbody>
	<%end%>
</table>
</div>
</body>
<script type="text/javascript">
	function sendCheckRequest(taskId){
		// console.log("Logged task ID "+taskId);
	$.ajax({
		url: '../insert_checkbox',
		type: "GET",
		data: {'task_id': taskId},
		dataType: "json",
		// success: function(data){
		// 	alert("Success");
		// },
		// error: function(data){
		// 	alert('Failure');
		// 	console.log(data.responseText);
		// }
	});
	location.reload();
}





</script>

app/views/home/nav.html.erb
<!-- <head>
  
  <link rel="stylesheet" href="app/assets/stylesheets/navbar.css">
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light" >
  <div class='container-fluid' bgcolor="black">
    <a class="navbar-brand" bgcolor="black">
    AVALON
    
  </a>
    <a class='navbar-brand' >
      <span class='bright' style="color:black"><%= current_user.name %>'s LOG</span>
    </a> 
    
    <ul class="nav navbar-nav navbar-right" ><span class="glyphicon glyphicon-user"></span>
      <% if logged_in?(:admin, :manager)%>
        <li class="nav-item">
         <%= link_to 'Home', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      
      
    </ul>
  </div>
</nav> -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>Horizontal Navigation Bar w/Rollover Effect</title> 
<style type="text/css"> 
<!-- 
 
 #navbar ul { 
  margin: 0; 
  padding: 5px; 
  list-style-type: none; 
  text-align: center; 
  background-color: black; 
  } 
 
#navbar ul li {  
  display: inline; 
  } 
 
#navbar ul li a { 
  text-decoration: none; 
  padding: .2em 1em; 
  color: #fff; 
  background-color: black; 
  } 
 
#navbar ul li a:hover { 
  color: #000; 
  background-color: grey; 
  } 
 
--> 
</style> 
</head> 
<body> 
<div id="navbar"> 
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: black;" >
    <div class="container-fluid">
    <a class="navbar-brand" bgcolor="black">
      <img src="http://www.avalonlabs.co/images/avalonlogo.png" class="img-fluid" style="height: auto; width: 27px; display:inline-block;">
     <font color="white">AVALON</font>
    </a>
     <a class='navbar-brand' >
      <!-- <img src="http://www.avalonlabs.co/images/avalonlogo.png" class="img-fluid" style="height: auto; width: auto; display:inline-block;"> -->
     <font color="white"><span class='bright' style="color:black"><font color="white"><%= current_user.name.upcase %>'s LOG</font></span>
    </a> 
  <ul class="nav navbar-nav navbar-right"> 
    <li class="nav-item">
         <%= link_to 'HOME', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
              <% if logged_in?(:admin, :manager)%>
        <li class="nav-item">
         <%= link_to 'USERS', team_lead_index_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
      <% end %>
    <% if logged_in?(:admin, :manager)%>
        <li class="nav-item">
         <%= link_to 'TIMINGS', department_change_time_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
      <% end %>

       
      <li class="nav-item">
        <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
  </ul> 
  </div>
</nav>
</div> 
</body> 
</html>