config/routes.rb
Rails.application.routes.draw do
 

get 'home/index'
# resources :user
  resources :tasks
resources :team_lead
resources :department
  #get 'team_lead/show'
   
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post '/tasks' => "tasks#create"
  root 'home#index'
  post '/department/change_time'
  get '/email' => "home#send_email"
  get '/insert_checkbox' => 'tasks#set_checkbox'
  post '/department/:id' => "department#change_time"
end



 

app/controllers/team_lead_controller.rb
class TeamLeadController < ApplicationController
	access admin: :all,manager: :all
	def index
		@users=User.all
		@departments = Department.all
	end
		
	def show
		@user = User.find(params[:id])
		if(logged_in?(:manager) && current_user.id != @user.id)
			redirect_to root_path
		end
		@tasks = @user.tasks
	  	@dates = @tasks.order(:date).group(:date).count
	  	@tasks_perday = @tasks.where(date: Time.now.strftime("%d/%m/%Y"))
	end

	
end

app/views/team_lead/index.html.erb
<head>
<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="background-image:url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBBEXXmQ3THutGt2YCWLPfc3bG7hpDl8lpA5qCN1Pp8fiwT04X7g)">

<%= render :template => "/home/nav" %>
<div class="container">
	
	<table class = "table" style="background-image: url(http://www.bestcoaching.com.mx/cartas/wp-content/uploads/2016/01/black-background-92475-1024x640.jpg)">
	 <thead align="center">	<tr>
	 		<th>
			<font color="grey"><b>NAME</b></font>
		</th>
		<th>
			<font color="grey"><b>DEPARTMENT</b></font>
		</th>
		<th>
			<font color="grey"><b>ACTION</b></font>
		</th>
	 	</tr>
	 </thead>
	 	<% @users.each do |user| %>
		 	<% @department_id = user.department_id%>
		 	<% dept_name = Department.find(@department_id).dept_name %>
		 	<% @current_department = @current_user.dept_name%>
		 	<% if logged_in?(:manager)%>
				<% if @current_department == @department%>
					<tr>
			 			<td align="center">
			 			<font color="white">	<%=user.name%> </font>
			 			</td>
			 			<td align="center">
			 			<font color="white">	<%= dept_name%>	 		</font>		
			 			</td>
			 			<td align="center" colspan="3">
			 				<%=link_to "View",team_lead_path(user)%>
			 			</td>
	 				</tr>
				<%end%>
			<% else%>
				<tr>
		 			<td align="center">
		 			<font color="white">	<%=user.name%></font>
		 			</td>
		 			<td align="center">
		 			<font color="white">	<%= dept_name%>	 	</font>			
		 			</td>
		 			<td align="center" colspan="3">
		 				<%=link_to "View" ,team_lead_path(user)%>
		 			</td>
 				</tr>
			<%end%>
	 	<%end%>
	 </table>
	</div>
</body>

app/views/team_lead/show.html.erb
<head>
<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body style="background-image:url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBBEXXmQ3THutGt2YCWLPfc3bG7hpDl8lpA5qCN1Pp8fiwT04X7g)">


	<%= render :template => "/home/nav" %>
 <div class="container">
 	<%=link_to "BACK" , team_lead_index_path%><br>
	<table class = "table" style="background-image: url(http://www.bestcoaching.com.mx/cartas/wp-content/uploads/2016/01/black-background-92475-1024x640.jpg)">
 	<thead align="center">
		<tr>
		<th>
			<font color="grey"><b>Date</b></font>
		</th>
		<th>
			<font color="grey"><b>TASKS</b></font>
		</th>
		<th>
			<font color="grey"><b>TASKS DONE</b></font>
		</th>
		</tr>
	</thead>
	<% @dates.each do |date| %>
	<tbody align="center">
		<tr>
			<td>
				<font color="grey">	<%= date[0].to_date.strftime("%B %d %Y") %> </font>
			</td>
			<td>
				<%@tasks.where(date: date).each do |task|%> 
				 <% if task.what_to_do != "previousdate" %>
				 	<font color="white"><%=task.what_to_do%></font></br>
				    <font color="grey">(<%= (task.created_at).localtime.to_date.strftime("%B %d %Y") %></font> <font color="grey"><%= (task.created_at).localtime.strftime("%I:%M %P") %> )</font><br>
				
				<%end%>

				<%end%>
			</td>
				
			<td>
				<%@tasks.where(date: date).each do |task|%>
				<%if(task.checkbox)%>
				 <%if task.what_to_do == 'previousdate'%>
					<font color="white"><%=task.what_done%></font><br>
					<font color="grey">(<%= (task.updated_at).localtime.to_date.strftime("%B %d %Y")%></font> <font color="grey"><%= (task.updated_at).localtime.strftime("%I:%M %P") %> )</font><br>
				<%else%>
					<font color="white"><%=task.what_to_do%></font><br>
					<font color="grey">(<%= (task.updated_at).localtime.to_date.strftime("%B %d %Y")%></font> <font color="grey"><%= (task.updated_at).localtime.strftime("%I:%M %P") %> )</font><br>
					<%end%>
				<%end%>
				<%end%>
			</td>
		</tr>
	</tbody>
	<%end%>
</table>
</div>
</body>
	